### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by tonyaellie** [tonyaellie/logger#4]
- [ ] integrate discord logging (moved to separate service)
	- [ ] rate limit discord logging
	- [ ] use an environment variable for discord channel and creds
	- [ ] create a seperate area for logs and channels for each application
	- [ ] only log errors and warnings
- [x] send logs to console in dev
- [x] dont send logs to console in production
